import Link from 'next/link';
import { notFound } from 'next/navigation';
import { eq } from 'drizzle-orm';
import { z } from 'zod';
import { PageHeader } from '@/components/page-header';
import { getDb } from '@/db/client';
import { leakageCategories } from '@/db/enums';
import { deals, orders } from '@/db/schema';
import {
  addClaimLineAction, applyPendingCreditAction, closeClaimAction, decideClaimLineAction, linkClaimCaseAction,
  recordClaimEventAction, recordClaimOfferAction, recordClaimPositionAction,
  recordNextActionAction, settleClaimAction,
} from '@/features/claims/actions';
import { claimCaseOptions, getClaimDetail } from '@/features/claims/service';
import { requireUser } from '@/lib/authorization';
import { taipeiDate } from '@/lib/business-date';

const card = 'rounded-xl border border-slate-200 bg-white p-5 shadow-sm';
const control = 'mt-1 w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm';
const button = 'rounded-md bg-brand px-4 py-2 text-sm font-semibold text-white hover:bg-slate-700';

export default async function ClaimPage({ params, searchParams }: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ error?: string; notice?: string }>;
}) {
  const [{ id }, query, user] = await Promise.all([params, searchParams, requireUser()]);
  if (!z.string().uuid().safeParse(id).success) notFound();
  const detail = await getClaimDetail(id);
  if (!detail) notFound();
  const claim = detail.claim;
  const canEdit = ['admin', 'manager', 'sales', 'finance'].includes(user.role);
  const canSettle = ['admin', 'manager', 'finance'].includes(user.role);
  const open = !['settled', 'closed'].includes(claim.status);
  const agentOrders = claim.pendingCredit ? await getDb().select({ id: orders.id, piNumber: orders.piNumber })
    .from(orders).innerJoin(deals, eq(deals.id, orders.dealId))
    .where(eq(deals.partnerId, claim.partnerId)) : [];
  const caseOptions = await claimCaseOptions(claim.partnerId);
  return <div className="space-y-6">
    <Link href="/claims" className="text-sm text-brand hover:underline">← Claims register</Link>
    <PageHeader eyebrow="COMMERCIAL / CLAIM" title={`${claim.claimNumber} · ${detail.modelCode} / ${detail.serialNumber}`} description={`${detail.partnerName} · ${claim.category.replaceAll('_', ' ')} · received ${claim.receivedAt}`} />
    {query.error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-800">{query.error}</p>}
    {query.notice && <p role="status" className="rounded-md border border-green-200 bg-green-50 p-4 text-sm text-green-800">{query.notice}</p>}
    <section className={card}><div className="flex flex-wrap justify-between gap-4"><div><h2 className="font-semibold">Claim summary</h2><p className="mt-2 text-sm">{claim.description}</p></div><a href={`/api/partners/${claim.partnerId}/briefing?visitDate=${taipeiDate()}`} target="_blank" rel="noreferrer" className="text-sm text-brand underline">Print agent briefing PDF</a></div>
      <dl className="mt-4 grid gap-3 text-sm md:grid-cols-3"><div><dt className="text-muted">Status</dt><dd className="font-medium">{claim.status.replaceAll('_', ' ')}{claim.pendingCredit ? ' · pending credit' : ''}</dd></div><div><dt className="text-muted">Claimed</dt><dd>{claim.claimedCurrency} {claim.claimedAmount}</dd></div><div><dt className="text-muted">Offered</dt><dd>{claim.offeredCurrency ?? '—'} {claim.offeredAmount ?? ''}</dd></div><div><dt className="text-muted">Settled</dt><dd>{claim.settledCurrency ?? '—'} {claim.settledAmount ?? ''}</dd></div><div><dt className="text-muted">Responsibility</dt><dd>{claim.responsibility.replaceAll('_', ' ')}</dd></div><div><dt className="text-muted">Source reference</dt><dd>{claim.sourceReference ?? '—'}</dd></div><div><dt className="text-muted">Contractual / actual ship</dt><dd>{detail.contractualDeliveryDate ?? '—'} / {detail.shippedAt?.toISOString().slice(0, 10) ?? '—'}</dd></div><div><dt className="text-muted">Kao Ming position</dt><dd>{claim.kaoMingPosition ?? 'Not stated'}</dd></div><div><dt className="text-muted">Next action</dt><dd>{claim.nextAction ?? 'Not recorded'}</dd></div></dl>
      {detail.leakage && <p className="mt-4 rounded-md bg-amber-50 p-3 text-sm">G20 leakage: {detail.leakage.category.replaceAll('_', ' ')} · {detail.leakage.currency} {detail.leakage.amount} · {detail.leakage.recoveryStatus}</p>}
      <div className="mt-4 text-sm">Service case: {claim.linkedCaseId ? <Link href={`/cases/${claim.linkedCaseId}`} className="text-brand underline">{caseOptions.find((entry) => entry.id === claim.linkedCaseId)?.number ?? 'Open linked case'}</Link> : 'None'}
        {canEdit && caseOptions.length > 0 && <form action={linkClaimCaseAction} className="mt-2 flex flex-wrap items-end gap-2">
          <input type="hidden" name="claimId" value={id} /><label>Link a case<select name="caseId" required defaultValue={claim.linkedCaseId ?? ''} className={control}><option value="">Select case</option>
            {caseOptions.filter((entry) => !entry.machineId || entry.machineId === claim.machineId).map((entry) =>
              <option key={entry.id} value={entry.id}>{entry.number} · {entry.subject}</option>)}</select></label>
          <button className="text-brand underline">Link case</button></form>}</div>
    </section>
    <section className={card}><h2 className="font-semibold">Claimed items / 請款項目</h2><div className="mt-3 space-y-3">{detail.lines.map((line) => <div key={line.id} className="rounded-md border border-slate-200 p-3 text-sm"><p><strong>#{line.lineNo} {line.description}</strong> · {line.currency} {line.amount} · {line.accepted == null ? 'undecided' : line.accepted ? 'accepted' : 'not accepted'}</p>{line.notes && <p className="mt-1 text-muted">{line.notes}</p>}{canSettle && open && <form action={decideClaimLineAction} className="mt-3 flex flex-wrap items-end gap-3"><input type="hidden" name="claimId" value={id} /><input type="hidden" name="lineId" value={line.id} /><label>Decision<select name="accepted" defaultValue={line.accepted == null ? '' : String(line.accepted)} required className={control}><option value="">Choose</option><option value="true">Accepted</option><option value="false">Rejected</option></select></label><label>Position notes<input name="notes" defaultValue={line.notes ?? ''} className={control} /></label><button className="text-brand underline">Save line decision</button></form>}</div>)}</div>
      {canEdit && open && <form action={addClaimLineAction} className="mt-5 grid gap-3 border-t pt-4 md:grid-cols-4"><input type="hidden" name="claimId" value={id} /><label className="text-sm md:col-span-2">Item description<input name="description" required className={control} /></label><label className="text-sm">Amount<input name="amount" inputMode="decimal" required className={control} /></label><label className="text-sm">Currency<input name="currency" defaultValue={claim.claimedCurrency} maxLength={3} required className={control} /></label><label className="text-sm md:col-span-3">Notes<input name="notes" className={control} /></label><div className="self-end"><button className={button}>Add claimed item</button></div></form>}
    </section>
    {canEdit && open && <section className={card}><h2 className="font-semibold">Position, next action and offer</h2><div className="mt-4 grid gap-6 md:grid-cols-2"><form action={recordClaimPositionAction} className="space-y-3"><input type="hidden" name="claimId" value={id} /><label className="block text-sm">Kao Ming position<textarea name="position" required rows={3} defaultValue={claim.kaoMingPosition ?? ''} className={control} /></label><label className="block text-sm">Position stated on<input name="occurredAt" type="date" required defaultValue={taipeiDate()} className={control} /></label><button className={button}>Record position</button></form><div className="space-y-5"><form action={recordNextActionAction} className="space-y-3"><input type="hidden" name="claimId" value={id} /><label className="block text-sm">Next action · owned by you<input name="nextAction" required defaultValue={claim.nextAction ?? ''} className={control} /></label><button className={button}>Save next action</button></form>{canSettle && <form action={recordClaimOfferAction} className="flex flex-wrap items-end gap-3"><input type="hidden" name="claimId" value={id} /><label className="text-sm">Offer amount<input name="amount" inputMode="decimal" required defaultValue={claim.offeredAmount ?? ''} className={control} /></label><label className="text-sm">Currency<input name="currency" maxLength={3} required defaultValue={claim.offeredCurrency ?? claim.claimedCurrency} className={control} /></label><button className={button}>Record offer</button></form>}</div></div></section>}
    <section className={card}><h2 className="font-semibold">Events / 往來紀錄</h2><div className="mt-3 space-y-2">{detail.events.map((event) => <div key={event.id} className="rounded-md bg-slate-50 p-3 text-sm"><span className="font-medium">{event.occurredAt} · {event.eventType.replaceAll('_', ' ')}</span><p>{event.summary}</p>{event.attachmentUrl && <p className="text-xs text-muted">Attachment: {event.attachmentUrl}</p>}</div>)}</div>
      {canEdit && claim.status !== 'closed' && <form action={recordClaimEventAction} className="mt-5 grid gap-3 border-t pt-4 md:grid-cols-2"><input type="hidden" name="claimId" value={id} /><label className="text-sm">Event<select name="eventType" className={control}>{['meeting', 'counter_offer', 'agreed', 'rejected', 'position_sent'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm">Occurred on<input name="occurredAt" type="date" required defaultValue={taipeiDate()} className={control} /></label><label className="text-sm md:col-span-2">Summary<textarea name="summary" required rows={2} className={control} /></label><label className="text-sm">Attachment reference<input name="attachmentUrl" className={control} /></label><div className="self-end"><button className={button}>Record event</button></div></form>}
    </section>
    {canSettle && open && <section className={card}><h2 className="font-semibold">Settle claim · G19 / G20 / G21</h2><p className="mt-1 text-sm text-muted">Record the agreed amount and method. Kao Ming responsibility also creates one linked leakage entry. Credit notes stay pending until applied to another order.</p><form action={settleClaimAction} className="mt-4 grid gap-3 md:grid-cols-3"><input type="hidden" name="claimId" value={id} /><label className="text-sm">Method<select name="method" required defaultValue="" className={control}><option value="">Choose method</option>{['cash', 'credit_note', 'free_goods', 'cost_share', 'rejected'].map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></label><label className="text-sm">Settled amount<input name="amount" inputMode="decimal" required className={control} /></label><label className="text-sm">Currency<input name="currency" maxLength={3} required defaultValue={claim.claimedCurrency} className={control} /></label><label className="text-sm md:col-span-2">Final outcome<input name="outcome" className={control} /></label><label className="text-sm">Cost share percent<input name="costSharePct" type="number" min="0" max="100" step="0.01" className={control} /></label><label className="text-sm">USD per settlement currency unit<input name="fxRate" inputMode="decimal" className={control} /></label><label className="text-sm">FX rate date<input name="fxRateDate" type="date" className={control} /></label>{claim.responsibility === 'kao_ming' && <><label className="text-sm">Leakage category<select name="leakageCategory" className={control}><option value="">Select category</option>{leakageCategories.map((value) => <option key={value} value={value}>{value.replaceAll('_', ' ')}</option>)}</select></label><label className="text-sm">Recovery status<select name="recoveryStatus" className={control}><option value="">Select recovery status</option>{['absorbed', 'claimed', 'recovered', 'chargeable_unbilled'].map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm">Loss incurred on<input name="incurredOn" type="date" className={control} /></label></>}<div className="md:col-span-3"><button className={button}>Record settlement</button></div></form></section>}
    {claim.pendingCredit && canSettle && <section className={card}><h2 className="font-semibold">Pending credit note · G21</h2><p className="mt-1 text-sm text-muted">{claim.settledCurrency} {claim.settledAmount} remains open until applied to a later order for {detail.partnerName}.</p><form action={applyPendingCreditAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="claimId" value={id} /><label className="text-sm">Apply to order<select name="orderId" required className={control}><option value="">Choose order</option>{agentOrders.filter((order) => order.id !== claim.orderId).map((order) => <option key={order.id} value={order.id}>{order.piNumber}</option>)}</select></label><button className={button}>Apply credit</button></form></section>}
    {claim.status === 'settled' && ['admin', 'manager'].includes(user.role) && <form action={closeClaimAction}><input type="hidden" name="claimId" value={id} /><button className={button}>Close claim</button>{claim.pendingCredit && <p className="mt-2 text-sm text-amber-700">G21 keeps this claim open until its credit is applied.</p>}</form>}
  </div>;
}
