import os
from pathlib import Path
from secrets import token_urlsafe
from time import time
from urllib.parse import urlparse
from playwright.sync_api import expect, sync_playwright


ROOT = Path(__file__).resolve().parents[2]
env_file = Path(os.environ.get("E2E_ENV_FILE", ROOT / ".local" / "e2e.env"))
env = dict(line.split("=", 1) for line in env_file.read_text(encoding="utf-8").splitlines() if "=" in line)
if not urlparse(env["DATABASE_URL"]).path.endswith("_e2e"):
    raise RuntimeError("Phase 1 browser checks require an isolated _e2e database")
BASE = env["AUTH_URL"].rstrip("/")
SUFFIX = str(int(time()))


def visit(page, path):
    page.goto(BASE + path)
    page.wait_for_load_state("networkidle")


def login(page, email, password):
    visit(page, "/login")
    page.get_by_label("Email").fill(email)
    page.get_by_label("Password").fill(password)
    page.get_by_role("button", name="Sign in").click()
    expect(page).to_have_url(BASE + "/", timeout=15000)


with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=True, executable_path=os.environ.get("CHROME_PATH", r"C:\Program Files\Google\Chrome\Application\chrome.exe"))
    page = browser.new_page(viewport={"width": 1440, "height": 900})
    try:
        login(page, env["SEED_ADMIN_EMAIL"], env["SEED_ADMIN_PASSWORD"])
        print("Administrator sign-in: passed")
        page.get_by_label("Language").select_option("zh-Hant")
        page.get_by_role("button", name="Apply").click()
        expect(page.get_by_role("link", name="首頁")).to_be_visible(timeout=10000)
        page.get_by_label("語言").select_option("en")
        page.get_by_role("button", name="套用").click()
        expect(page.get_by_role("link", name="Home")).to_be_visible(timeout=10000)
        print("English/Traditional Chinese locale switching: passed")

        partner_code = "AT-P-" + SUFFIX
        visit(page, "/partners/new")
        page.get_by_label("Code", exact=True).fill(partner_code)
        page.get_by_label("Name", exact=True).fill("Acceptance Agent " + SUFFIX)
        page.get_by_label("Chinese name").fill("驗收代理商")
        page.get_by_label("Country code").fill("TW")
        page.get_by_role("button", name="Add partner").click()
        expect(page.get_by_text("Partner saved")).to_be_visible(timeout=10000)
        visit(page, "/partners")
        page.get_by_role("link", name=partner_code).click()
        expect(page.get_by_label("Name", exact=True)).to_have_value("Acceptance Agent " + SUFFIX)
        page.get_by_label("Name", exact=True).fill("Acceptance Agent Updated " + SUFFIX)
        page.get_by_role("button", name="Save changes").click()
        expect(page.get_by_text("Partner saved")).to_be_visible(timeout=10000)
        page.reload()
        expect(page.get_by_label("Name", exact=True)).to_have_value("Acceptance Agent Updated " + SUFFIX)
        page.get_by_label("Voltage").fill("380V")
        page.get_by_label("Frequency").fill("50Hz")
        page.get_by_label("Phase").fill("3相")
        page.get_by_label("CE variant").fill("CE")
        page.get_by_label("Label languages").fill("English, Chinese")
        page.get_by_label("Colour codes").fill("KM-101")
        page.get_by_label("Agent nameplate applied").check()
        page.get_by_role("button", name="Save profile").click()
        expect(page.get_by_text("Compliance profile saved")).to_be_visible(timeout=10000)
        visit(page, "/partners")
        expect(page.get_by_role("row").filter(has_text=partner_code)).to_contain_text("Complete")
        page.get_by_role("link", name=partner_code).click()
        page.get_by_label("Lifecycle status").select_option("terminated")
        page.get_by_role("button", name="Save changes").click()
        expect(page.get_by_text("Partner saved")).to_be_visible(timeout=10000)
        visit(page, "/partners")
        expect(page.get_by_role("row").filter(has_text=partner_code)).to_contain_text("Terminated")
        print("Partner create/update, compliance profile, and lifecycle termination: passed")

        model_code = "AT-M-" + SUFFIX
        visit(page, "/products/models?new=1")
        page.get_by_label("Code", exact=True).fill(model_code)
        page.get_by_label("Product line").fill("gantry")
        page.get_by_label("English name").fill("Acceptance model")
        page.get_by_label("Chinese name").fill("驗收機型")
        page.get_by_role("button", name="Add machine model").click()
        expect(page.get_by_text("Machine model saved")).to_be_visible(timeout=10000)
        visit(page, "/products/models")
        page.get_by_role("link", name=model_code).click()
        page.get_by_label("English name").fill("Acceptance model updated")
        page.get_by_role("button", name="Save changes").click()
        expect(page.get_by_text("Machine model saved")).to_be_visible(timeout=10000)
        print("Machine model create/update: passed")

        item_code = "AT-I-" + SUFFIX
        visit(page, "/products/items?new=1")
        page.get_by_label("Code", exact=True).fill(item_code)
        page.get_by_label("TYPE").select_option("spec_change")
        page.get_by_label("English name").fill("Acceptance spindle change")
        page.get_by_label("Chinese name").fill("驗收主軸變更")
        page.get_by_label("Spec category").select_option(index=1)
        page.get_by_label("Machine model").select_option(label=model_code)
        page.get_by_label("English replacement value").fill("12000 rpm")
        page.get_by_label("Chinese replacement value").fill("12000 轉")
        page.get_by_role("button", name="Add item").click()
        expect(page.get_by_text("Item saved")).to_be_visible(timeout=10000)
        visit(page, "/products/items")
        expect(page.get_by_role("row").filter(has_text=item_code)).to_contain_text("驗收主軸變更")
        page.get_by_role("link", name=item_code).click()
        page.get_by_label("English name").fill("Acceptance spindle change updated")
        page.get_by_role("button", name="Save changes").click()
        expect(page.get_by_text("Item saved")).to_be_visible(timeout=10000)
        page.reload()
        expect(page.get_by_label("English name")).to_have_value("Acceptance spindle change updated")
        page.once("dialog", lambda dialog: dialog.accept())
        page.get_by_role("button", name="Archive").click()
        expect(page).to_have_url(BASE + "/products/items", timeout=10000)
        visit(page, "/products/items")
        expect(page.get_by_role("link", name=item_code)).to_have_count(0)
        print("Bilingual item create/update/archive: passed")

        visit(page, "/products/models")
        page.get_by_role("link", name=model_code).click()
        page.get_by_label("Active model").uncheck()
        page.get_by_role("button", name="Save changes").click()
        expect(page.get_by_text("Machine model saved")).to_be_visible(timeout=10000)
        visit(page, "/products/models")
        expect(page.get_by_role("row").filter(has_text=model_code)).to_contain_text("Inactive")
        print("Machine model deactivation: passed")

        version_name = "AT-BOOK-" + SUFFIX
        visit(page, "/products/price-books?new=1")
        page.get_by_label("Name", exact=True).fill(version_name)
        page.get_by_label("Effective from").fill("2027-01-01")
        page.get_by_label("Effective to").fill("2027-06-30")
        page.get_by_role("button", name="Add price book draft").click()
        expect(page.get_by_text("Price book draft saved")).to_be_visible(timeout=10000)
        visit(page, "/products/price-books")
        page.get_by_role("link", name=version_name).click()
        page.get_by_label("Effective to").fill("2027-12-31")
        page.get_by_role("button", name="Save changes").click()
        expect(page.get_by_text("Price book draft saved")).to_be_visible(timeout=10000)
        page.reload()
        expect(page.get_by_label("Effective to")).to_have_value("2027-12-31")
        page.once("dialog", lambda dialog: dialog.accept())
        page.get_by_role("button", name="Archive").click()
        expect(page).to_have_url(BASE + "/products/price-books", timeout=10000)
        visit(page, "/products/price-books")
        expect(page.get_by_role("link", name=version_name)).to_have_count(0)
        print("Price book draft create/update/archive: passed")

        sales_email = "acceptance-" + SUFFIX + "@kaoming.local"
        sales_password = token_urlsafe(20)
        visit(page, "/settings")
        page.get_by_label("Name", exact=True).fill("Acceptance Sales")
        page.get_by_label("Email").fill(sales_email)
        page.get_by_label("Initial password").fill(sales_password)
        page.get_by_label("Role").select_option("sales")
        page.get_by_role("button", name="Add user").click()
        expect(page.get_by_text("User account created")).to_be_visible(timeout=10000)
        page.get_by_role("button", name="Sign out").click()
        expect(page).to_have_url(BASE + "/login")
        login(page, sales_email, sales_password)
        visit(page, "/settings")
        expect(page.locator("body")).to_contain_text("404")
        visit(page, "/products/models?new=1")
        expect(page.get_by_role("button", name="Add machine model")).to_have_count(0)
        page.get_by_role("button", name="Sign out").click()
        expect(page).to_have_url(BASE + "/login")
        login(page, env["SEED_ADMIN_EMAIL"], env["SEED_ADMIN_PASSWORD"])
        visit(page, "/settings")
        row = page.get_by_role("row").filter(has_text=sales_email)
        page.once("dialog", lambda dialog: dialog.accept())
        row.get_by_role("button", name="Deactivate").click()
        expect(row).to_contain_text("Inactive", timeout=10000)
        page.get_by_role("button", name="Sign out").click()
        expect(page).to_have_url(BASE + "/login")
        page.get_by_label("Email").fill(sales_email)
        page.get_by_label("Password").fill(sales_password)
        page.get_by_role("button", name="Sign in").click()
        expect(page.get_by_text("Email or password was not accepted")).to_be_visible(timeout=10000)
        print("User provisioning, role restriction, and deactivation: passed")
    except Exception:
        page.screenshot(path=str(ROOT / ".local" / "phase1-e2e-failure.png"), full_page=True)
        print("Failed at:", page.url)
        raise
    finally:
        browser.close()
