import Link from 'next/link';
import { notFound } from 'next/navigation';
import { z } from 'zod';
import { bookingDelayCauses } from '@/db/enums';
import { PageHeader } from '@/components/page-header';
import { getDeal } from '@/features/deals/queries';
import { getDeliveryState } from '@/features/delivery/service';
import {
  addConditionPhotoAction, addShipmentConditionPhotoAction, closeSiteVisitAction, createSiteVisitAction, markArrivedAction,
  markShippedAction, prepareShipmentAction, recordAcceptanceAction, recordFinalPaymentAction,
  recordPackageAction,
} from '@/features/delivery/actions';
import { getDealOrder } from '@/features/orders/service';
import { getLogisticsState } from '@/features/logistics/service';
import {
  confirmBookingAction, issueShippingNoticeAction, issueShippingOrderAction, notifyCompletionAction,
  recordShippingNoticeSentAction, recordShippingOrderPrintedAction, recordBookingDelayCauseAction, rejectBookingAction,
  requestBookingAction, uploadExportDocumentAction,
} from '@/features/logistics/actions';
import { requireUser } from '@/lib/authorization';

const card = 'rounded-xl border border-slate-200 bg-white p-5 shadow-sm';
const control = 'mt-1 w-full rounded-md border border-slate-300 bg-white px-3 py-2 text-sm';
const button = 'rounded-md bg-brand px-4 py-2 text-sm font-semibold text-white hover:bg-slate-700';

export default async function DeliveryPage({ params, searchParams }: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ error?: string; notice?: string }>;
}) {
  const [{ id }, query, user] = await Promise.all([params, searchParams, requireUser()]);
  if (!z.string().uuid().safeParse(id).success) notFound();
  const [deal, order] = await Promise.all([getDeal(id), getDealOrder(id)]);
  if (!deal) notFound();
  const state = order ? await getDeliveryState(order.id) : null;
  const shipment = state?.shipment;
  const logistics = shipment ? await getLogisticsState(shipment.id) : null;
  const machine = state?.machine;
  const canShip = ['admin', 'manager', 'logistics'].includes(user.role);
  const canPay = ['admin', 'manager', 'finance'].includes(user.role);
  const canService = ['admin', 'manager', 'service'].includes(user.role);
  return <div className="space-y-6">
    <Link href={`/deals/${id}`} className="text-sm text-brand hover:underline">← {deal.dealNumber}</Link>
    <PageHeader eyebrow="DEAL / DELIVERY" title="Shipment and installed machine" description="Record payment, packing, shipment, arrival, installation visits and acceptance as separate events." />
    {query.error && <p role="alert" className="rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-800">{query.error}</p>}
    {query.notice && <p role="status" className="rounded-md border border-green-200 bg-green-50 p-4 text-sm text-green-800">{query.notice}</p>}
    {!order && <section className={card}>Record a customer PO before opening a shipment.</section>}
    {order && !shipment && canShip && <section className={card}><h2 className="font-semibold">Prepare shipment</h2><form action={prepareShipmentAction} className="mt-4"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="orderId" value={order.id} /><button className={button}>Open shipment record</button></form></section>}
    {shipment && <section className={card}><h2 className="font-semibold">Shipment · {order?.piNumber}</h2>
      <dl className="mt-3 grid gap-3 text-sm md:grid-cols-2"><div><dt className="text-muted">Final payment</dt><dd>{shipment.finalPaymentReceivedAt?.toISOString().slice(0, 10) ?? 'Pending'}</dd></div><div><dt className="text-muted">Packing</dt><dd>{shipment.grossWeightKg ? `${shipment.grossWeightKg} kg · ${shipment.packageLengthMm} × ${shipment.packageWidthMm} × ${shipment.packageHeightMm} mm` : 'Pending'}{shipment.requiresShippingMark ? ' · Shipping mark required' : ''}</dd></div><div><dt className="text-muted">Shipped</dt><dd>{shipment.shippedAt?.toISOString().slice(0, 10) ?? 'Pending'}</dd></div><div><dt className="text-muted">Arrived</dt><dd>{shipment.arrivedAt?.toISOString().slice(0, 10) ?? 'Pending'}</dd></div></dl>
      {canPay && !shipment.finalPaymentReceivedAt && <form action={recordFinalPaymentAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><label className="text-sm">Final payment received amount · {order?.currency}<input name="amount" type="number" min="0.01" max={order?.orderValue} step="0.01" required className={control} /></label><button className={button}>Record final payment received</button></form>}
      {canShip && !shipment.shippedAt && <form action={recordPackageAction} className="mt-5 grid gap-3 md:grid-cols-3"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><label className="text-sm">Forwarder<input name="forwarderName" defaultValue={shipment.forwarderName ?? ''} className={control} /></label><label className="text-sm">Length mm<input name="lengthMm" type="number" min="1" required defaultValue={shipment.packageLengthMm ?? ''} className={control} /></label><label className="text-sm">Width mm<input name="widthMm" type="number" min="1" required defaultValue={shipment.packageWidthMm ?? ''} className={control} /></label><label className="text-sm">Height mm<input name="heightMm" type="number" min="1" required defaultValue={shipment.packageHeightMm ?? ''} className={control} /></label><label className="text-sm">Gross kg<input name="grossWeightKg" type="number" min="0.01" step="0.01" required defaultValue={shipment.grossWeightKg ?? ''} className={control} /></label><div className="self-end"><button className={button}>Save package</button></div></form>}
      {canShip && !shipment.shippedAt && <form action={markShippedAction} className="mt-5 grid gap-3 border-t pt-5 md:grid-cols-2"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><label className="text-sm">Machine serial number<input name="serialNumber" required defaultValue={shipment.plannedSerialNumber ?? ''} className={control} /></label><label className="text-sm">Bill of lading reference<input name="billOfLadingRef" required className={control} /></label><div className="md:col-span-2"><button className={button}>Record shipment and create machine</button></div></form>}
      {canShip && shipment.shippedAt && !shipment.arrivedAt && <form action={markArrivedAction} className="mt-5"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><button className={button}>Record arrival</button></form>}
    </section>}
    {shipment && <section className={card}><h2 className="font-semibold">FAT and loading condition photos</h2>
      <p className="mt-1 text-sm text-slate-600">Photos taken before shipment stay with this shipment and attach to the machine when its serial is registered.</p>
      <div className="mt-3 flex flex-wrap gap-3">{state?.shipmentPhotos.map((photo) => <a key={photo.id} href={photo.fileUrl} target="_blank" rel="noreferrer" className="rounded border border-slate-200 p-2 text-sm text-brand underline">{photo.capturePoint.toUpperCase()} · {photo.filename}{photo.caption ? ` · ${photo.caption}` : ''}</a>)}{!state?.shipmentPhotos.length && <span className="text-sm text-slate-500">No shipment photos yet.</span>}</div>
      {(canShip || canService) && !shipment.shippedAt && <form action={addShipmentConditionPhotoAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><label className="text-sm">Capture point<select name="capturePoint" className={control}><option value="fat">FAT</option><option value="loading">Loading</option></select></label><label className="text-sm">Photo<input name="photo" type="file" accept="image/png,image/jpeg" required className={control} /></label><label className="text-sm">Caption<input name="caption" className={control} /></label><button className={button}>Add shipment photo</button></form>}
    </section>}
    {shipment && <section className={card}><h2 className="font-semibold">Logistics E0–E8</h2>
      <p className="mt-2 text-sm text-muted">{shipment.incoterm ?? 'Incoterm pending'} · Forwarder appointed by {shipment.forwarderNominatedBy ?? 'review needed'} · Booking due by {shipment.bookingDueBy ?? 'delivery date missing'} · Delay cause {shipment.bookingDelayCause?.replaceAll('_', ' ') ?? 'none recorded'}</p>
      <ol className="mt-4 grid gap-2 text-sm md:grid-cols-3">{[
        ['E0 Completion notified', shipment.completionNotifiedAt], ['E1 Final payment', shipment.finalPaymentReceivedAt],
        ['E2 Booking requested', shipment.bookingRequestedAt], ['E3 Space confirmed', shipment.bookingConfirmedAt],
        ['E4 Notice sent', shipment.shippingNoticeSentAt], ['E5 Export documents', shipment.exportDocumentsPreparedAt],
        ['E6 出貨單 printed', shipment.shippingOrderPrintedAt], ['E7 Shipped', shipment.shippedAt], ['E8 Arrived', shipment.arrivedAt],
      ].map(([label, value]) => <li key={label as string} className={`rounded-md border p-3 ${value ? 'border-green-200 bg-green-50' : 'border-slate-200 bg-slate-50'}`}>{label as string}<span className="block text-xs text-muted">{value instanceof Date ? value.toISOString().slice(0, 10) : 'Pending'}</span></li>)}</ol>
      {canShip && !shipment.completionNotifiedAt && <form action={notifyCompletionAction} className="mt-5 flex flex-wrap items-end gap-3"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><label className="text-sm">Actual production finish<input type="date" name="actualFinish" required className={control} /></label><button className={button}>Record E0 completion notice</button></form>}
      {canShip && shipment.completionNotifiedAt && !shipment.bookingConfirmedAt && (!shipment.bookingRequestedAt || logistics?.attempts.at(-1)?.rejectedAt) && <form action={requestBookingAction} className="mt-5"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><button className={button}>Request booking · attempt {shipment.bookingAttempts + 1}</button></form>}
      {logistics && logistics.attempts.length > 0 && <div className="mt-5"><h3 className="font-medium">Booking attempts</h3>{logistics.attempts.map((attempt) => <p key={attempt.id} className="mt-2 text-sm">#{attempt.attemptNumber} · requested {attempt.requestedAt.toISOString().slice(0, 10)} · {attempt.confirmedAt ? `confirmed ${attempt.bookingReference}` : attempt.rejectedAt ? `rejected: ${attempt.rejectionReason}` : 'awaiting confirmation'}</p>)}</div>}
      {canShip && shipment.bookingRequestedAt && !shipment.bookingConfirmedAt && !logistics?.attempts.at(-1)?.rejectedAt && <div className="mt-5 grid gap-4 border-t pt-4 md:grid-cols-2"><form action={confirmBookingAction} className="grid gap-3 md:col-span-2 md:grid-cols-2"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><label className="text-sm">Booking reference<input name="bookingReference" required className={control} /></label><label className="text-sm">Vessel / flight<input name="vesselOrFlight" required className={control} /></label><label className="text-sm">ETD<input name="etd" type="date" required className={control} /></label><label className="text-sm">ETA<input name="eta" type="date" required className={control} /></label><label className="text-sm">Delay cause · required if booking is late<select name="delayCause" required={Boolean(shipment.bookingDueBy && new Date().toISOString().slice(0, 10) > shipment.bookingDueBy)} className={control}><option value="">No delay</option>{bookingDelayCauses.map((cause) => <option key={cause} value={cause}>{cause.replaceAll('_', ' ')}</option>)}</select></label><div className="md:col-span-2"><button className={button}>Confirm space · G14</button></div></form><form action={rejectBookingAction} className="flex flex-wrap items-end gap-3 md:col-span-2"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><label className="text-sm">Refusal reason<input name="reason" required className={control} /></label><button className="rounded-md border border-slate-300 px-4 py-2 text-sm">Record refusal and retry</button></form></div>}
      {canShip && shipment.bookingDueBy && (shipment.bookingConfirmedAt
        ? shipment.bookingConfirmedAt.toISOString().slice(0, 10) > shipment.bookingDueBy
        : new Date().toISOString().slice(0, 10) > shipment.bookingDueBy)
        && <form action={recordBookingDelayCauseAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><label className="text-sm">Booking delay cause<select name="delayCause" defaultValue={shipment.bookingDelayCause ?? ''} required className={control}><option value="">Choose cause</option>{bookingDelayCauses.map((cause) => <option key={cause} value={cause}>{cause.replaceAll('_', ' ')}</option>)}</select></label><button className={button}>Save delay cause</button></form>}
      {canShip && shipment.bookingConfirmedAt && !shipment.shippingNoticeDocumentId && <form action={issueShippingNoticeAction} className="mt-5"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><button className={button}>Issue 出貨通知 PDF · G15</button></form>}
      {shipment.shippingNoticeDocumentId && <div className="mt-4 flex flex-wrap items-center gap-4 text-sm"><a href={`/api/documents/${shipment.shippingNoticeDocumentId}/pdf`} target="_blank" rel="noreferrer" className="text-brand underline">Open shipping notice PDF</a>{canShip && !shipment.shippingNoticeSentAt && <form action={recordShippingNoticeSentAction}><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><button className={button}>Record notice sent</button></form>}</div>}
      {shipment.bookingConfirmedAt && <div className="mt-5 border-t pt-4"><h3 className="font-medium">Export documents</h3><div className="mt-3 space-y-2">{(['commercial_invoice', 'packing_list', 'certificate_of_origin'] as const).map((kind) => { const doc = logistics?.exports.find((entry) => entry.kind === kind); return <div key={kind} className="rounded-md bg-slate-50 p-3 text-sm"><span className="font-medium">{kind.replaceAll('_', ' ')}</span>{doc && <a href={`/api/shipment-export-documents/${doc.id}`} className="ml-3 text-brand underline">{doc.filename}</a>}{canShip && !shipment.shippedAt && <form action={uploadExportDocumentAction} className="mt-2 flex flex-wrap items-end gap-2"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><input type="hidden" name="kind" value={kind} /><input type="file" name="document" accept="application/pdf,.pdf" required className="text-sm" /><button className="text-brand underline">Upload PDF</button></form>}</div>; })}</div></div>}
      {canShip && shipment.exportDocumentsPreparedAt && shipment.shippingNoticeSentAt && !shipment.shippingOrderDocumentId && <form action={issueShippingOrderAction} className="mt-5 flex flex-wrap items-end gap-3"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><label className="text-sm">Machine serial on 出貨單<input name="serialNumber" required className={control} /></label><button className={button}>Issue 出貨單 PDF · G16</button></form>}
      {shipment.shippingOrderDocumentId && <div className="mt-4 flex flex-wrap items-center gap-4 text-sm"><a href={`/api/documents/${shipment.shippingOrderDocumentId}/pdf`} target="_blank" rel="noreferrer" className="text-brand underline">Open 出貨單 PDF</a>{canShip && !shipment.shippingOrderPrintedAt && <form action={recordShippingOrderPrintedAction}><input type="hidden" name="dealId" value={id} /><input type="hidden" name="shipmentId" value={shipment.id} /><button className={button}>Record printed 出貨單</button></form>}</div>}
    </section>}
    {machine && <section className={card}><h2 className="font-semibold">Machine {machine.serialNumber}</h2><p className="mt-2 text-sm text-muted">Accepted {machine.acceptedAt ?? 'pending'} · Warranty {machine.warrantyMonths ?? '—'} months · Expires {machine.warrantyExpiresAt ?? 'pending'}</p>
      {canService && !machine.acceptedAt && <form action={recordAcceptanceAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="machineId" value={machine.id} /><label className="text-sm">Accepted on<input name="acceptedAt" type="date" required className={control} /></label><button className={button}>Record acceptance and start warranty</button></form>}
    </section>}
    {machine && <section className={card}><h2 className="font-semibold">Site visits and condition photos</h2>
      <div className="mt-3 space-y-4">{state!.visits.map((visit) => { const photos = state!.photos.filter((photo) => photo.siteVisitId === visit.id); return <div key={visit.id} className="rounded-md border border-slate-200 p-4"><h3 className="font-medium">{visit.visitType} · {visit.visitedAt}</h3><p className="mt-1 text-sm text-muted">{visit.engineer} · {visit.closedAt ? 'Closed' : 'Open'} · {photos.length} photos</p>{visit.workPerformed && <p className="mt-2 text-sm">{visit.workPerformed}</p>}
        <div className="mt-3 flex flex-wrap gap-3">{photos.map((photo) => <a key={photo.id} href={photo.fileUrl} target="_blank" rel="noreferrer" className="text-sm text-brand underline">{photo.filename}{photo.caption ? ` · ${photo.caption}` : ''}</a>)}</div>
        {canService && !visit.closedAt && <><form action={addConditionPhotoAction} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="machineId" value={machine.id} /><input type="hidden" name="visitId" value={visit.id} /><input type="hidden" name="capturePoint" value={visit.visitType === 'installation' ? 'installation' : 'service'} /><label className="text-sm">Photo<input name="photo" type="file" accept="image/png,image/jpeg" required className={control} /></label><label className="text-sm">Caption<input name="caption" className={control} /></label><button className={button}>Add photo</button></form><form action={closeSiteVisitAction} className="mt-3 flex flex-wrap items-end gap-3"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="visitId" value={visit.id} /><label className="text-sm">Acknowledged by<input name="acknowledgedBy" className={control} /></label><button className={button}>Close visit</button></form></>}
      </div>; })}</div>
      {canService && <form action={createSiteVisitAction} className="mt-5 grid gap-3 border-t pt-5 md:grid-cols-2"><input type="hidden" name="dealId" value={id} /><input type="hidden" name="machineId" value={machine.id} /><label className="text-sm">Visit type<select name="visitType" className={control}>{['installation', 'warranty', 'chargeable', 'inspection'].map((type) => <option key={type}>{type}</option>)}</select></label><label className="text-sm">Visited on<input name="visitedAt" type="date" required className={control} /></label><label className="text-sm">Engineer<input name="engineer" required className={control} /></label><label className="text-sm">Work performed<textarea name="workPerformed" className={control} /></label><div className="md:col-span-2"><button className={button}>Open site visit</button></div></form>}
    </section>}
  </div>;
}
